language: go
go:
- 1.7
- master
sudo: false
before_script:
- 'mkdir -p $GOPATH/bin && wget -q https://github.com/barnybug/gohome/releases/download/1.0.0/upx -O $GOPATH/bin/upx && chmod +x $GOPATH/bin/upx'
script:
- make test
after_success:
- make release
deploy:
  provider: releases
  api_key:
    secure: au903BSPYC2wwVko8Hxxp1SS9SK7FYdQqZC4AfVWz1Odj+6K4X5ilzkJvcesk9amJWltpbUb+SxzCx7+Tnrfvw+ZwJXe6N6bNAEkml0OkwgMUH3ylbOqGUgsfmChyiJwCPG6Q2ve0k48nZIPjCKnHOBG65hNlhqIeFcq2HY/Dzw=
  file: 
  - release/gohome-linux-amd64
  - release/gohome-linux-386
  - release/gohome-linux-arm
  on:
    repo: barnybug/gohome
    tags: true
    go: 1.7
