language: go
go:
 - 1.3
 - 1.4

before_install:
# libzmq version 4
- sudo add-apt-repository -y ppa:chris-lea/zeromq
- sudo apt-get update -qq
- sudo apt-get install -qq libzmq3 libzmq3-dev
script:
- make deps test
