# An example configuration for gohome
# To upload this to redis initially, do:
# redis-cli -x set gohome/config < config.yml
endpoints:
  # at least one endpoint should be defined
  mqtt:
    broker: tcp://127.0.0.1:1883

bill:
  electricity:
    primary_rate: 8.89
    standing_charge: 35.5
  gas:
    calorific_value: 39.3
    conversion_factor: 1.02264
    multiplier: 0.01
    primary_rate: 3.16
    standing_charge: 35.4
  vat: 5
  currency: £
devices:
  light.kitchen:
    group: downstairs
    name: Kitchen
    type: light
earth:
  latitude: 51.5072
  longitude: 0.1275
espeak:
  args: -s 140
general:
  email:
    admin: admin@example.com
    from: me@example.com
    server: localhost:25
heating:
  device: heater.boiler
  zones:
    hallway:
      schedule:
        Monday,Tuesday,Wednesday,Thursday,Friday:
        - '0:00': 0
        Saturday,Sunday:
        - '9:00': 15.5
        - '22:30': 10
    living:
      schedule:
        Friday:
        - '7:45': 16
        - '8:10': 14
        - '16:45': 17
        - '22:20': 10
        Monday,Tuesday,Wednesday,Thursday:
        - '7:40': 16.5
        - '8:10': 14
        - '17:30': 17
        - '22:15': 10
        Saturday,Sunday:
        - '9:00': 16
        - '22:50': 10
    office:
      schedule:
        Monday,Tuesday,Wednesday,Thursday,Friday:
        - '9:00': 16
        - '18:00': 10
        Saturday,Sunday:
        - '0:00': 0
  minimum: 10
  slop: 0.1
irrigation:
  at: 6h
  device: pump.garden
  enabled: true
  factor: 1.5
  interval: 12h
  max_temp: 25
  max_time: 60
  min_temp: 13
  min_time: 10
jabber:
  jid: myjabberid@gmail.com/gohome
  pass: password
sms:
  telephone: '+441234567890'
twitter:
  auth:
    consumer_key: xxx
    consumer_secret: yyy
    token: aaa
    token_secret: bbb
voice:
  'lights? on':
    switch living on
  'lights? off':
    switch living off
  'blanket on':
    switch blanket on
  'blanket off':
    switch blanket off
watchdog:
  devices:
    power.power: 5m
    temp.garden: 20m
    temp.hallway: 4h
    temp.living: 20m
    temp.office: 20m
    temp.outside: 20m
    wind.outside: 20m
  processes: [api, arduino, automata, bills, camera, currentcost, datalogger, earth, espeaker, graphite, heating, irrigation, jabber, pubsub, rfid, rfxtrx, sms, twitter, watchdog, weather, wmr100, wunderground, xpl]

weather:
  outside:
    rain: rain.outside
    temp: temp.garden
    wind: wind.outside
  windy: 3.2
wunderground:
  id: STATIONID
  password: password
  url: http://weatherstation.wunderground.com/weatherstation/updateweatherstation.php
